service: food-optimizer

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-1
  memorySize: 1024
  timeout: 30
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}

functions:
  analyze:
    handler: lambda_handler.handler
    events:
      - http:
          path: analyze
          method: post
          cors: true
